pages = [{"l":"index.html#","e":false,"i":"","n":"scalapb-ujson","t":"scalapb-ujson","d":"","k":"static"},
{"l":"scalapb/ujson.html#","e":false,"i":"","n":"scalapb.ujson","t":"scalapb.ujson","d":"","k":"package"},
{"l":"scalapb/ujson/JsonFormat$.html#","e":false,"i":"","n":"JsonFormat","t":"JsonFormat extends JsonFormat","d":"scalapb.ujson","k":"object"},
{"l":"scalapb/ujson/JsonFormat.html#","e":false,"i":"","n":"JsonFormat","t":"JsonFormat(val preserveProtoFieldNames: Boolean, val includeDefaultValueFields: Boolean, val formatEnumsAsNumbers: Boolean)","d":"scalapb.ujson","k":"class"},
{"l":"scalapb/ujson/JsonFormat.html#formatEnumsAsNumbers-0","e":false,"i":"","n":"formatEnumsAsNumbers","t":"formatEnumsAsNumbers: Boolean","d":"scalapb.ujson.JsonFormat","k":"val"},
{"l":"scalapb/ujson/JsonFormat.html#includeDefaultValueFields-0","e":false,"i":"","n":"includeDefaultValueFields","t":"includeDefaultValueFields: Boolean","d":"scalapb.ujson.JsonFormat","k":"val"},
{"l":"scalapb/ujson/JsonFormat.html#preserveProtoFieldNames-0","e":false,"i":"","n":"preserveProtoFieldNames","t":"preserveProtoFieldNames: Boolean","d":"scalapb.ujson.JsonFormat","k":"val"},
{"l":"scalapb/ujson/JsonFormat.html#read-67a","e":false,"i":"","n":"read","t":"read[A <: GeneratedMessage](json: Readable)(using companion: GeneratedMessageCompanion[A]): A","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat.html#write-a8c","e":false,"i":"","n":"write","t":"write(message: GeneratedMessage, indent: Int, escapeUnicode: Boolean): String","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat.html#writeTo-fffff7c2","e":false,"i":"","n":"writeTo","t":"writeTo(message: GeneratedMessage, out: Writer, indent: Int, escapeUnicode: Boolean): Unit","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat.html#writeToByteArray-7d9","e":false,"i":"","n":"writeToByteArray","t":"writeToByteArray(message: GeneratedMessage, indent: Int, escapeUnicode: Boolean): Array[Byte]","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat.html#writeToJson-fffffe79","e":false,"i":"","n":"writeToJson","t":"writeToJson(message: GeneratedMessage, indent: Int, escapeUnicode: Boolean): Value","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat.html#writeToOutputStream-fffff3b0","e":false,"i":"","n":"writeToOutputStream","t":"writeToOutputStream(message: GeneratedMessage, out: OutputStream, indent: Int, escapeUnicode: Boolean): Unit","d":"scalapb.ujson.JsonFormat","k":"def"},
{"l":"scalapb/ujson/JsonFormat$Writer$.html#","e":false,"i":"","n":"Writer","t":"Writer extends Transformer[GeneratedMessage]","d":"scalapb.ujson.JsonFormat","k":"object"},
{"l":"scalapb/ujson/JsonFormatException.html#","e":false,"i":"","n":"JsonFormatException","t":"JsonFormatException(msg: String, cause: Throwable) extends Exception","d":"scalapb.ujson","k":"class"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#","e":false,"i":"","n":"JsonFormatUtils","t":"JsonFormatUtils","d":"scalapb.ujson","k":"object"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#BoolValueDescriptor-0","e":false,"i":"","n":"BoolValueDescriptor","t":"BoolValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#BytesValueDescriptor-0","e":false,"i":"","n":"BytesValueDescriptor","t":"BytesValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#DoubleValueDescriptor-0","e":false,"i":"","n":"DoubleValueDescriptor","t":"DoubleValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#DurationDescriptor-0","e":false,"i":"","n":"DurationDescriptor","t":"DurationDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#FieldMaskDescriptor-0","e":false,"i":"","n":"FieldMaskDescriptor","t":"FieldMaskDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#FloatValueDescriptor-0","e":false,"i":"","n":"FloatValueDescriptor","t":"FloatValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#Int32ValueDescriptor-0","e":false,"i":"","n":"Int32ValueDescriptor","t":"Int32ValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#Int64ValueDescriptor-0","e":false,"i":"","n":"Int64ValueDescriptor","t":"Int64ValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#StringValueDescriptor-0","e":false,"i":"","n":"StringValueDescriptor","t":"StringValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#TimestampDescriptor-0","e":false,"i":"","n":"TimestampDescriptor","t":"TimestampDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#UInt32ValueDescriptor-0","e":false,"i":"","n":"UInt32ValueDescriptor","t":"UInt32ValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#UInt64ValueDescriptor-0","e":false,"i":"","n":"UInt64ValueDescriptor","t":"UInt64ValueDescriptor: String","d":"scalapb.ujson.JsonFormatUtils","k":"val"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#camelify-fffff2ca","e":false,"i":"","n":"camelify","t":"camelify(snake: String): String","d":"scalapb.ujson.JsonFormatUtils","k":"def"},
{"l":"scalapb/ujson/JsonFormatUtils$.html#defaultPrimitiveValue-fffff1aa","e":false,"i":"","n":"defaultPrimitiveValue","t":"defaultPrimitiveValue(fd: FieldDescriptor): PValue","d":"scalapb.ujson.JsonFormatUtils","k":"def"},
{"l":"scalapb/ujson/JsonReadException.html#","e":false,"i":"","n":"JsonReadException","t":"JsonReadException(val message: String, val position: Int, cause: Throwable) extends JsonFormatException","d":"scalapb.ujson","k":"class"},
{"l":"scalapb/ujson/JsonReadException.html#message-0","e":false,"i":"","n":"message","t":"message: String","d":"scalapb.ujson.JsonReadException","k":"val"},
{"l":"scalapb/ujson/JsonReadException.html#position-0","e":false,"i":"","n":"position","t":"position: Int","d":"scalapb.ujson.JsonReadException","k":"val"},
{"l":"scalapb/ujson/KeyVisitor$.html#","e":false,"i":"","n":"KeyVisitor","t":"KeyVisitor extends SimpleVisitor[_, String]","d":"scalapb.ujson","k":"object"},
{"l":"scalapb/ujson/KeyVisitor$.html#expectedMsg-0","e":false,"i":"","n":"expectedMsg","t":"expectedMsg: String","d":"scalapb.ujson.KeyVisitor","k":"val"},
{"l":"scalapb/ujson/NoOpVisitor$.html#","e":false,"i":"","n":"NoOpVisitor","t":"NoOpVisitor extends Visitor[PValue, PValue]","d":"scalapb.ujson","k":"object"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitArray-add","e":false,"i":"","n":"visitArray","t":"visitArray(length: Int, index: Int): ArrVisitor[PValue, PValue]","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitBinary-4d6","e":false,"i":"","n":"visitBinary","t":"visitBinary(bytes: Array[Byte], offset: Int, len: Int, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitChar-fffff1ca","e":false,"i":"","n":"visitChar","t":"visitChar(s: Char, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitExt-fffffe06","e":false,"i":"","n":"visitExt","t":"visitExt(tag: Byte, bytes: Array[Byte], offset: Int, len: Int, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFalse-fffff9a8","e":false,"i":"","n":"visitFalse","t":"visitFalse(index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFloat32-594","e":false,"i":"","n":"visitFloat32","t":"visitFloat32(d: Float, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFloat64-fffff16f","e":false,"i":"","n":"visitFloat64","t":"visitFloat64(d: Double, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFloat64String-fffff123","e":false,"i":"","n":"visitFloat64String","t":"visitFloat64String(s: String, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFloat64StringParts-fffff21d","e":false,"i":"","n":"visitFloat64StringParts","t":"visitFloat64StringParts(s: CharSequence, decIndex: Int, expIndex: Int, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitFloat64StringParts-fffff01c","e":false,"i":"","n":"visitFloat64StringParts","t":"visitFloat64StringParts(s: CharSequence, decIndex: Int, expIndex: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitInt16-6d4","e":false,"i":"","n":"visitInt16","t":"visitInt16(i: Short, index: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitInt32-121","e":false,"i":"","n":"visitInt32","t":"visitInt32(i: Int, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitInt64-fffffce4","e":false,"i":"","n":"visitInt64","t":"visitInt64(i: Long, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitInt8-bf0","e":false,"i":"","n":"visitInt8","t":"visitInt8(i: Byte, index: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitNull-fffff9a8","e":false,"i":"","n":"visitNull","t":"visitNull(index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitObject-fffffbf9","e":false,"i":"","n":"visitObject","t":"visitObject(length: Int, jsonableKeys: Boolean, index: Int): ObjVisitor[PValue, PValue]","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitString-53d","e":false,"i":"","n":"visitString","t":"visitString(s: CharSequence, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitTrue-fffff9a8","e":false,"i":"","n":"visitTrue","t":"visitTrue(index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitUInt16-6d4","e":false,"i":"","n":"visitUInt16","t":"visitUInt16(i: Short, index: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitUInt32-ac7","e":false,"i":"","n":"visitUInt32","t":"visitUInt32(i: Int, index: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitUInt64-fffffce4","e":false,"i":"","n":"visitUInt64","t":"visitUInt64(i: Long, index: Int): PValue","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/NoOpVisitor$.html#visitUInt8-bf0","e":false,"i":"","n":"visitUInt8","t":"visitUInt8(i: Byte, index: Int): PEmpty.type","d":"scalapb.ujson.NoOpVisitor","k":"def"},
{"l":"scalapb/ujson/Reader.html#","e":false,"i":"","n":"Reader","t":"Reader(md: Descriptor) extends SimpleVisitor[PValue, PMessage]","d":"scalapb.ujson","k":"class"},
{"l":"scalapb/ujson/Reader.html#expectedMsg-0","e":false,"i":"","n":"expectedMsg","t":"expectedMsg: String","d":"scalapb.ujson.Reader","k":"val"},
{"l":"scalapb/ujson/SimpleVisitor.html#","e":false,"i":"","n":"SimpleVisitor","t":"SimpleVisitor[-T, +V] extends Visitor[T, V]","d":"scalapb.ujson","k":"trait"},
{"l":"scalapb/ujson/SimpleVisitor.html#expectedMsg-0","e":false,"i":"","n":"expectedMsg","t":"expectedMsg: String","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitArray-add","e":false,"i":"","n":"visitArray","t":"visitArray(length: Int, index: Int): ArrVisitor[T, V]","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitBinary-fffff768","e":false,"i":"","n":"visitBinary","t":"visitBinary(bytes: Array[Byte], offset: Int, len: Int, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitChar-55c","e":false,"i":"","n":"visitChar","t":"visitChar(s: Char, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitExt-fffffc98","e":false,"i":"","n":"visitExt","t":"visitExt(tag: Byte, bytes: Array[Byte], offset: Int, len: Int, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitFalse-aba","e":false,"i":"","n":"visitFalse","t":"visitFalse(index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitFloat32-da6","e":false,"i":"","n":"visitFloat32","t":"visitFloat32(d: Float, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitFloat64-ffffff41","e":false,"i":"","n":"visitFloat64","t":"visitFloat64(d: Double, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitFloat64String-ff5","e":false,"i":"","n":"visitFloat64String","t":"visitFloat64String(s: String, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitFloat64StringParts-16f","e":false,"i":"","n":"visitFloat64StringParts","t":"visitFloat64StringParts(s: CharSequence, decIndex: Int, expIndex: Int, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitInt32-573","e":false,"i":"","n":"visitInt32","t":"visitInt32(i: Int, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitInt64-8f6","e":false,"i":"","n":"visitInt64","t":"visitInt64(i: Long, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitNull-aba","e":false,"i":"","n":"visitNull","t":"visitNull(index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitObject-fffffbf9","e":false,"i":"","n":"visitObject","t":"visitObject(length: Int, jsonableKeys: Boolean, index: Int): ObjVisitor[T, V]","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitString-fffffc8f","e":false,"i":"","n":"visitString","t":"visitString(s: CharSequence, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitTrue-aba","e":false,"i":"","n":"visitTrue","t":"visitTrue(index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/SimpleVisitor.html#visitUInt64-8f6","e":false,"i":"","n":"visitUInt64","t":"visitUInt64(i: Long, index: Int): V","d":"scalapb.ujson.SimpleVisitor","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#","e":false,"i":"","n":"TimeUtils","t":"TimeUtils","d":"scalapb.ujson","k":"object"},
{"l":"scalapb/ujson/TimeUtils$.html#formatNanos-78c","e":false,"i":"","n":"formatNanos","t":"formatNanos(nanos: Int): String","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#parseDuration-98e","e":false,"i":"","n":"parseDuration","t":"parseDuration(value: String): Duration","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#parseTimestamp-ede","e":false,"i":"","n":"parseTimestamp","t":"parseTimestamp(value: String): Timestamp","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#writeDuration-fffff538","e":false,"i":"","n":"writeDuration","t":"writeDuration(d: Duration): String","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#writeDuration-5c8","e":false,"i":"","n":"writeDuration","t":"writeDuration(seconds: Long, nanos: Int): String","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#writeTimestamp-fffffd48","e":false,"i":"","n":"writeTimestamp","t":"writeTimestamp(ts: Timestamp): String","d":"scalapb.ujson.TimeUtils","k":"def"},
{"l":"scalapb/ujson/TimeUtils$.html#writeTimestamp-5c8","e":false,"i":"","n":"writeTimestamp","t":"writeTimestamp(seconds: Long, nanos: Int): String","d":"scalapb.ujson.TimeUtils","k":"def"}];